In [1]:
import pandas as pd

In [7]:
df = pd.read_csv(r"C:\Users\prakash\Downloads\udemy_courses.csv")
df.head()

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5,2017-01-18T20:58:58Z,Business Finance
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39.0,2017-03-09T16:34:20Z,Business Finance
2,1006314,Financial Modeling for Business Analysts and C...,https://www.udemy.com/financial-modeling-for-b...,True,45,2174,74,51,Intermediate Level,2.5,2016-12-19T19:26:30Z,Business Finance
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,https://www.udemy.com/complete-excel-finance-c...,True,95,2451,11,36,All Levels,3.0,2017-05-30T20:07:24Z,Business Finance
4,1011058,How To Maximize Your Profits Trading Options,https://www.udemy.com/how-to-maximize-your-pro...,True,200,1276,45,26,Intermediate Level,2.0,2016-12-13T14:57:18Z,Business Finance

### 1.waht are all different subject for which udemy is offering courses?

In [10]:
#drop subject unique()

In [12]:
df.subject.unique()

array(['Business Finance', 'Graphic Design', 'Musical Instruments',
       'Web Development'], dtype=object)

### 2.which subject has the maximum number of courses.

In [15]:
#data.subject.value_counts()

In [17]:
 df.head(2)

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5,2017-01-18T20:58:58Z,Business Finance
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39.0,2017-03-09T16:34:20Z,Business Finance

In [19]:
df.drop(["url"],axis=1,inplace=True)
df

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,True,200,2147,23,51,All Levels,1.5,2017-01-18T20:58:58Z,Business Finance
1,1113822,Complete GST Course & Certification - Grow You...,True,75,2792,923,274,All Levels,39.0,2017-03-09T16:34:20Z,Business Finance
2,1006314,Financial Modeling for Business Analysts and C...,True,45,2174,74,51,Intermediate Level,2.5,2016-12-19T19:26:30Z,Business Finance
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,True,95,2451,11,36,All Levels,3.0,2017-05-30T20:07:24Z,Business Finance
4,1011058,How To Maximize Your Profits Trading Options,True,200,1276,45,26,Intermediate Level,2.0,2016-12-13T14:57:18Z,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...
3673,775618,Learn jQuery from Scratch - Master of JavaScri...,True,100,1040,14,21,All Levels,2.0,2016-06-14T17:36:46Z,Web Development
3674,1088178,How To Design A WordPress Website With No Codi...,True,25,306,3,42,Beginner Level,3.5,2017-03-10T22:24:30Z,Web Development
3675,635248,Learn and Build using Polymer,True,40,513,169,48,All Levels,3.5,2015-12-30T16:41:42Z,Web Development
3676,905096,CSS Animations: Create Amazing Effects on Your...,True,50,300,31,38,All Levels,3.0,2016-08-11T19:06:15Z,Web Development
3677,297602,Using MODX CMS to Build Websites: A Beginner's...,True,45,901,36,20,Beginner Level,2.0,2014-09-28T19:51:11Z,Web Development

In [23]:
df.subject.value_counts()

subject
Web Development        1200
Business Finance       1195
Musical Instruments     680
Graphic Design          603
Name: count, dtype: int64

### 3.Show all the courses which are Free of cost.

In [25]:
#data[data.is_paid==false]

In [27]:
df.head(2)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,True,200,2147,23,51,All Levels,1.5,2017-01-18T20:58:58Z,Business Finance
1,1113822,Complete GST Course & Certification - Grow You...,True,75,2792,923,274,All Levels,39.0,2017-03-09T16:34:20Z,Business Finance

In [33]:
df[df.is_paid == False]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
95,1148774,Options Trading 101: The Basics,False,0,1514,66,11,Beginner Level,0.550000,2017-03-23T22:19:57Z,Business Finance
103,133536,Stock Market Investing for Beginners,False,0,50855,2698,15,Beginner Level,1.500000,2013-12-25T19:53:34Z,Business Finance
106,265960,Fundamentals of Forex Trading,False,0,17160,620,23,All Levels,1.000000,2014-08-29T20:10:38Z,Business Finance
108,923616,Website Investing 101 - Buying & Selling Onlin...,False,0,6811,151,51,All Levels,2.000000,2016-08-05T17:03:15Z,Business Finance
112,191854,Stock Market Foundations,False,0,19339,794,9,Beginner Level,2.000000,2014-03-31T21:35:06Z,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...
3638,155640,Building a Search Engine in PHP & MySQL,False,0,10110,379,12,All Levels,2.500000,2014-02-03T18:07:52Z,Web Development
3643,366720,CSS Image filters - The modern web images colo...,False,0,6315,53,16,All Levels,1.500000,2014-12-10T19:43:40Z,Web Development
3651,1079078,Drupal 8 Site Building,False,0,1942,23,48,All Levels,4.500000,2017-05-02T05:15:52Z,Web Development
3665,21386,Beginner Photoshop to HTML5 and CSS3,False,0,73110,1716,22,All Levels,2.000000,2012-07-27T12:54:57Z,Web Development
3668,270976,A how to guide in HTML,False,0,7318,205,8,Beginner Level,0.583333,2014-08-10T20:19:10Z,Web Development

### 4.show all the courses which are paid

In [36]:
#data[data.is_paid == True]

In [38]:
df[df.is_paid == True]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,True,200,2147,23,51,All Levels,1.5,2017-01-18T20:58:58Z,Business Finance
1,1113822,Complete GST Course & Certification - Grow You...,True,75,2792,923,274,All Levels,39.0,2017-03-09T16:34:20Z,Business Finance
2,1006314,Financial Modeling for Business Analysts and C...,True,45,2174,74,51,Intermediate Level,2.5,2016-12-19T19:26:30Z,Business Finance
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,True,95,2451,11,36,All Levels,3.0,2017-05-30T20:07:24Z,Business Finance
4,1011058,How To Maximize Your Profits Trading Options,True,200,1276,45,26,Intermediate Level,2.0,2016-12-13T14:57:18Z,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...
3673,775618,Learn jQuery from Scratch - Master of JavaScri...,True,100,1040,14,21,All Levels,2.0,2016-06-14T17:36:46Z,Web Development
3674,1088178,How To Design A WordPress Website With No Codi...,True,25,306,3,42,Beginner Level,3.5,2017-03-10T22:24:30Z,Web Development
3675,635248,Learn and Build using Polymer,True,40,513,169,48,All Levels,3.5,2015-12-30T16:41:42Z,Web Development
3676,905096,CSS Animations: Create Amazing Effects on Your...,True,50,300,31,38,All Levels,3.0,2016-08-11T19:06:15Z,Web Development
3677,297602,Using MODX CMS to Build Websites: A Beginner's...,True,45,901,36,20,Beginner Level,2.0,2014-09-28T19:51:11Z,Web Development

### 5.Which Top selling courses?

In [41]:
#df.sort_values['num_subcribers',ascending = False)

In [47]:
df.sort_values('num_subscribers',ascending = False)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
2827,41295,Learn HTML5 Programming From Scratch,False,0,268923,8629,45,All Levels,10.500000,2013-02-14T07:03:41Z,Web Development
3032,59014,Coding for Entrepreneurs Basic,False,0,161029,279,27,Beginner Level,3.500000,2013-06-09T15:51:55Z,Web Development
3230,625204,The Web Developer Bootcamp,True,200,121584,27445,342,All Levels,43.000000,2015-11-02T21:13:27Z,Web Development
2783,173548,Build Your First Website in 1 Week with HTML5 ...,False,0,120291,5924,30,Beginner Level,3.000000,2014-04-08T16:21:30Z,Web Development
3232,764164,The Complete Web Developer Course 2.0,True,200,114512,22412,304,All Levels,30.500000,2016-03-08T22:28:36Z,Web Development
...,...,...,...,...,...,...,...,...,...,...,...
1569,726314,Create Beautiful Image Maps for Your Website,True,20,0,0,8,Intermediate Level,0.616667,2016-01-18T17:56:36Z,Graphic Design
1473,185526,MicroStation - Células,True,20,0,0,9,Beginner Level,0.616667,2014-04-15T21:48:55Z,Graphic Design
1472,181268,Photoshop: Creando elemental de aire,True,20,0,0,5,Beginner Level,1.000000,2014-04-01T21:50:32Z,Graphic Design
1471,188584,Letras en Adobe Illustrator,True,40,0,0,13,Beginner Level,2.500000,2014-04-04T21:23:23Z,Graphic Design
2405,1265814,ABRSM Grade III Piano Class - Handel Sonatina ...,True,20,0,0,5,Beginner Level,0.516667,2017-07-06T16:12:34Z,Musical Instruments

### 6.Which are Least selling courses?

In [52]:
#df.sort_values('num_subscribers')

In [54]:
df.sort_values('num_subscribers')

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
885,1032648,beginning accounting,True,20,0,0,12,Intermediate Level,0.633333,2016-12-26T16:52:47Z,Business Finance
456,1247992,Introduction to Project Management for Finance...,True,50,0,0,9,Beginner Level,2.000000,2017-07-03T21:40:32Z,Business Finance
457,1251582,Best Practices in Corporate Budgeting,True,50,0,0,9,Intermediate Level,2.000000,2017-06-29T22:01:56Z,Business Finance
458,1258666,Financial Statement Auditing Cycles,True,50,0,0,9,Intermediate Level,2.000000,2017-06-29T23:20:10Z,Business Finance
459,1168172,Case studies on credit appraisal for bankers,True,20,0,0,15,Beginner Level,3.500000,2017-05-01T20:16:26Z,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...
3232,764164,The Complete Web Developer Course 2.0,True,200,114512,22412,304,All Levels,30.500000,2016-03-08T22:28:36Z,Web Development
2783,173548,Build Your First Website in 1 Week with HTML5 ...,False,0,120291,5924,30,Beginner Level,3.000000,2014-04-08T16:21:30Z,Web Development
3230,625204,The Web Developer Bootcamp,True,200,121584,27445,342,All Levels,43.000000,2015-11-02T21:13:27Z,Web Development
3032,59014,Coding for Entrepreneurs Basic,False,0,161029,279,27,Beginner Level,3.500000,2013-06-09T15:51:55Z,Web Development
2827,41295,Learn HTML5 Programming From Scratch,False,0,268923,8629,45,All Levels,10.500000,2013-02-14T07:03:41Z,Web Development

### 7.Show all courses of Graphic design where the price is below 100?

In [59]:
#df[(df.subject == 'Graphic Design') & (df.price < '100')]

In [61]:
df.head(1)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,True,200,2147,23,51,All Levels,1.5,2017-01-18T20:58:58Z,Business Finance

In [95]:
df[(df.subject == 'Graphic Design') & (df.price < 100) ]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
1196,1197206,Illustrator CC MasterClass,True,95,462,50,86,All Levels,12.0,2017-05-02T16:41:21Z,Graphic Design
1198,1219520,Adobe Illustrator T-Shirt Design for Merch by ...,True,20,390,44,15,All Levels,1.0,2017-06-13T20:41:14Z,Graphic Design
1202,28556,Discover How to Draw and paint Comics,True,65,8901,424,85,All Levels,62.0,2012-11-21T22:03:54Z,Graphic Design
1203,317278,Typographic Logos: Typography and Lettering fo...,True,25,4235,427,20,Intermediate Level,1.5,2014-10-16T19:30:01Z,Graphic Design
1204,573064,Photoshop in Ease: Create World Amazing Graph...,True,20,14440,182,26,All Levels,3.0,2015-08-13T21:17:34Z,Graphic Design
...,...,...,...,...,...,...,...,...,...,...,...
1793,456388,Adobe Photoshop CC | The Essential Guide,True,20,254,5,81,All Levels,4.5,2015-05-12T00:19:27Z,Graphic Design
1794,955242,Learn to Composite a 2D Action Shot in Photoshop,True,20,40,2,8,Beginner Level,1.5,2016-09-10T21:38:26Z,Graphic Design
1795,496430,Infographic Design: How To Create Your Own Inf...,True,20,84,8,13,All Levels,2.0,2015-05-12T20:38:58Z,Graphic Design
1796,793246,Autodesk Inventor 2016 : Complete Guide,True,20,23,4,83,Beginner Level,7.5,2016-03-22T20:35:56Z,Graphic Design
1797,547190,Amazing Graphic Design for Beginners,True,20,32,10,5,Beginner Level,0.7,2015-07-08T19:58:01Z,Graphic Design

In [97]:
 df[(df.subject == 'Graphic Design') & (df.price ==  100) ]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
1248,1160004,Design a logo for FREE in Inkscape,True,100,1148,26,42,All Levels,2.000000,2017-05-01T18:32:43Z,Graphic Design
1288,927186,Learn Blender 3D - The introduction course,True,100,739,12,15,Beginner Level,1.500000,2016-08-19T00:52:30Z,Graphic Design
1338,638040,Adobe Photoshop Essentials: Master Adobe Photo...,True,100,1373,5,63,Beginner Level,2.500000,2015-11-18T17:47:26Z,Graphic Design
1347,1246168,"Illustrator para criação de peças gráficas, De...",True,100,33,3,41,Beginner Level,1.500000,2017-06-13T04:15:20Z,Graphic Design
1376,654038,How To Sell Your Art Online With ETSY,True,100,1338,38,35,Beginner Level,3.000000,2015-11-11T01:26:13Z,Graphic Design
1380,1243016,Photoshop - Tratamento de pele profissional,True,100,50,5,16,Intermediate Level,1.500000,2017-06-06T14:22:28Z,Graphic Design
1381,1266468,Indesign - Para quem quer trabalhar com Design...,True,100,27,7,12,Intermediate Level,2.500000,2017-06-27T02:48:29Z,Graphic Design
1417,978462,Blender Modelling Series - Volume Two,True,100,1526,3,24,Beginner Level,2.000000,2016-10-12T20:22:14Z,Graphic Design
1452,1027080,Logo Portfolio in 1 Hour in Wordpress,True,100,734,9,36,All Levels,1.000000,2016-12-06T22:13:44Z,Graphic Design
1489,482924,Mastering Retouching and Restoration (15 proje...,True,100,4927,15,22,All Levels,2.500000,2015-04-26T12:27:22Z,Graphic Design
1507,1161864,Diseño impreso - Preimpresión para offset en I...,True,100,33,9,29,All Levels,1.500000,2017-05-31T18:37:31Z,Graphic Design
1540,490392,Getting Started with Illustrator CC,True,100,92,10,57,Beginner Level,5.500000,2015-05-01T21:29:51Z,Graphic Design
1577,1012262,Icon & Logo Symbol Design in Adobe Illustrator,True,100,1043,27,30,All Levels,2.000000,2016-11-23T22:57:18Z,Graphic Design
1585,727510,How To Become An Etsy Wholesale Seller,True,100,1013,0,25,Beginner Level,2.500000,2016-03-29T22:34:30Z,Graphic Design
1614,575040,Typography From A to Z,True,100,317,15,76,All Levels,6.000000,2015-08-07T22:16:26Z,Graphic Design
1628,950894,photoshop - CURSO DE PHOTOSHOP DO BÁSICO AO AV...,True,100,1110,183,77,All Levels,10.000000,2017-02-06T17:22:18Z,Graphic Design
1632,908664,Word Swag : Create Stunning Images with the Wo...,True,100,2416,19,14,All Levels,1.000000,2016-08-09T17:56:53Z,Graphic Design
1657,757900,Canva : Book Cover Design,True,100,3377,20,15,Beginner Level,2.000000,2016-02-26T01:08:20Z,Graphic Design
1665,1269190,7 Secrets To Designing In Black and White,True,100,1000,1,12,All Levels,1.500000,2017-06-27T19:55:18Z,Graphic Design
1672,1147664,Photoshop CC Eğitim Seti (YENİ),True,100,27,5,202,All Levels,16.000000,2017-03-30T22:26:26Z,Graphic Design
1693,983444,Adobe Illustrator Vectors For Hand Letterers,True,100,23,2,9,Beginner Level,0.616667,2016-10-21T18:50:38Z,Graphic Design
1706,996868,How to Design a Logo in Adobe Illustrator,True,100,972,44,24,All Levels,1.000000,2016-11-14T15:26:17Z,Graphic Design
1745,771044,"Make Money With Photoshop: Logos, Business Car...",True,100,32,4,21,All Levels,5.000000,2016-08-14T22:05:04Z,Graphic Design

### 8.List out all the courses that are related with 'Python'.

In [100]:
#df[df.courses_title.contains9('Python') ]

In [102]:
df.head(1)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,True,200,2147,23,51,All Levels,1.5,2017-01-18T20:58:58Z,Business Finance

In [110]:
df[df.course_title.str.contains('Python')]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
14,1196544,Python Algo Trading: Sentiment Trading with News,True,200,294,19,42,All Levels,7.0,2017-04-28T16:41:44Z,Business Finance
30,1170894,Python Algo Stock Trading: Automate Your Trading!,True,95,1165,21,41,Beginner Level,2.5,2017-05-28T23:41:03Z,Business Finance
41,1035472,Python for Finance: Investment Fundamentals & ...,True,195,3811,278,103,All Levels,6.5,2017-03-30T22:17:09Z,Business Finance
147,1070886,Python Algo Trading: FX Trading with Oanda,True,200,453,42,33,Intermediate Level,3.0,2017-03-14T00:39:45Z,Business Finance
334,815482,Stock Technical Analysis with Python,True,50,409,35,46,All Levels,8.0,2016-04-12T00:40:03Z,Business Finance
536,529828,Python for Trading & Investing,True,95,638,25,36,All Levels,5.0,2015-06-17T22:23:31Z,Business Finance
762,1088656,Quantitative Trading Analysis with Python,True,50,256,17,49,All Levels,5.5,2017-01-27T17:11:28Z,Business Finance
863,902888,Investment Portfolio Analysis with Python,True,50,209,13,37,All Levels,7.0,2016-07-13T21:40:32Z,Business Finance
1682,546848,Learn to code in Python and learn Adobe Photos...,True,50,1132,1,29,All Levels,2.0,2015-07-08T00:15:12Z,Graphic Design
2497,16646,Web Programming with Python,True,50,35267,217,53,All Levels,4.0,2012-04-25T00:01:43Z,Web Development
2528,391546,Learn Python and Django: Payment Processing,True,70,17714,198,23,All Levels,3.5,2015-02-09T15:37:56Z,Web Development
2553,938560,The Complete Ethical Hacking Course 2.0: Pytho...,True,195,7827,268,66,All Levels,11.0,2016-09-26T15:08:29Z,Web Development
2570,47963,"Coding for Entrepreneurs: Learn Python, Django...",True,195,23412,799,251,All Levels,45.0,2013-04-08T00:46:14Z,Web Development
2681,477702,Python for Beginners: Python Programming Langu...,True,150,6153,125,84,Beginner Level,5.0,2015-06-14T18:18:57Z,Web Development
2960,270808,Projects in Django and Python,True,60,1764,53,28,All Levels,6.5,2014-10-21T07:58:07Z,Web Development
3133,574082,"Web Scraping with Python, Ruby & import. io",True,75,973,50,46,All Levels,4.5,2015-08-09T22:16:41Z,Web Development
3138,631128,Complete Python Web Course: Build 8 Python Web...,True,110,7489,941,173,All Levels,16.0,2015-11-08T20:57:35Z,Web Development
3160,368340,Professional Python Web Development Using Flask,True,120,3420,489,102,Beginner Level,14.5,2015-03-04T00:10:36Z,Web Development
3192,1035940,Professional RESTful API Design using Python F...,True,120,578,25,36,Intermediate Level,4.5,2017-01-11T21:15:25Z,Web Development
3194,1063722,Learn Python Django - A Hands-On Course,True,50,1339,21,18,Beginner Level,2.0,2017-01-18T21:53:34Z,Web Development
3197,76052,Try Django 1.9 | Build a Blog and Learn Python...,True,50,7407,172,147,All Levels,20.0,2014-03-04T07:12:21Z,Web Development
3200,822444,Python and Django Full Stack Web Developer Boo...,True,200,11832,1883,191,All Levels,31.5,2017-02-24T18:40:55Z,Web Development
3203,970600,REST APIs with Flask and Python,True,110,5151,737,115,Intermediate Level,12.5,2016-11-06T19:00:38Z,Web Development
3284,599504,Advanced Scalable Python Web Development Using...,True,120,1299,56,71,Intermediate Level,14.0,2016-08-11T22:09:24Z,Web Development
3326,186096,"Core: A Web App Reference Guide for Django, Py...",True,195,2497,98,154,All Levels,26.0,2014-05-29T00:58:43Z,Web Development
3333,1038538,Introduction to QGIS Python Programming,True,85,197,26,28,Beginner Level,3.5,2016-12-22T00:11:22Z,Web Development
3343,523312,Python Web Programming,True,100,1020,46,60,Beginner Level,6.0,2015-07-01T21:46:36Z,Web Development
3392,70640,Python Programming: Create an Digital Marketpl...,True,195,4198,145,161,All Levels,26.0,2013-10-20T19:53:28Z,Web Development
3507,394832,Fun and creative web engineering with Python a...,False,0,10917,319,25,All Levels,2.0,2015-06-09T19:51:50Z,Web Development

In [112]:
len(df[df.course_title.str.contains('Python')])

29

### 9.What are courses that published in year 2015?

In [ ]:
#df.dtypes
#df['published_timestamp'] = pd.to_datetime(df.published_timestamp)
#df.dtypes
#df['year'] = df['published_timestamp'].dt.year
#df[df.year == 2015]

In [116]:
df.head(1)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,True,200,2147,23,51,All Levels,1.5,2017-01-18T20:58:58Z,Business Finance

In [118]:
df.dtypes

course_id                int64
course_title            object
is_paid                   bool
price                    int64
num_subscribers          int64
num_reviews              int64
num_lectures             int64
level                   object
content_duration       float64
published_timestamp     object
subject                 object
dtype: object

In [121]:
df['published_timestamp'] = pd.to_datetime(df.published_timestamp)

In [123]:
df.dtypes

course_id                            int64
course_title                        object
is_paid                               bool
price                                int64
num_subscribers                      int64
num_reviews                          int64
num_lectures                         int64
level                               object
content_duration                   float64
published_timestamp    datetime64[ns, UTC]
subject                             object
dtype: object

In [125]:
df.head(1)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,True,200,2147,23,51,All Levels,1.5,2017-01-18 20:58:58+00:00,Business Finance

In [127]:
#df['year'] = df['published_timestamp'].dt.year

df['year'] = df['published_timestamp'].dt.year
df

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,year
0,1070968,Ultimate Investment Banking Course,True,200,2147,23,51,All Levels,1.5,2017-01-18 20:58:58+00:00,Business Finance,2017
1,1113822,Complete GST Course & Certification - Grow You...,True,75,2792,923,274,All Levels,39.0,2017-03-09 16:34:20+00:00,Business Finance,2017
2,1006314,Financial Modeling for Business Analysts and C...,True,45,2174,74,51,Intermediate Level,2.5,2016-12-19 19:26:30+00:00,Business Finance,2016
3,1210588,Beginner to Pro - Financial Analysis in Excel ...,True,95,2451,11,36,All Levels,3.0,2017-05-30 20:07:24+00:00,Business Finance,2017
4,1011058,How To Maximize Your Profits Trading Options,True,200,1276,45,26,Intermediate Level,2.0,2016-12-13 14:57:18+00:00,Business Finance,2016
...,...,...,...,...,...,...,...,...,...,...,...,...
3673,775618,Learn jQuery from Scratch - Master of JavaScri...,True,100,1040,14,21,All Levels,2.0,2016-06-14 17:36:46+00:00,Web Development,2016
3674,1088178,How To Design A WordPress Website With No Codi...,True,25,306,3,42,Beginner Level,3.5,2017-03-10 22:24:30+00:00,Web Development,2017
3675,635248,Learn and Build using Polymer,True,40,513,169,48,All Levels,3.5,2015-12-30 16:41:42+00:00,Web Development,2015
3676,905096,CSS Animations: Create Amazing Effects on Your...,True,50,300,31,38,All Levels,3.0,2016-08-11 19:06:15+00:00,Web Development,2016
3677,297602,Using MODX CMS to Build Websites: A Beginner's...,True,45,901,36,20,Beginner Level,2.0,2014-09-28 19:51:11+00:00,Web Development,2014

In [129]:
df[df.year == 2015]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,year
7,403100,"Trading Stock Chart Patterns For Immediate, Ex...",True,95,2917,148,23,All Levels,2.5,2015-01-30 22:13:03+00:00,Business Finance,2015
8,476268,Options Trading 3 : Advanced Stock Profit and ...,True,195,5172,34,38,Expert Level,2.5,2015-05-28 00:14:03+00:00,Business Finance,2015
10,592338,Forex Trading Secrets of the Pros With Amazon'...,True,200,4284,93,76,All Levels,5.0,2015-09-11 16:47:02+00:00,Business Finance,2015
15,504036,Short Selling: Learn To Sell Stocks Before The...,True,75,2276,106,19,Intermediate Level,1.5,2015-06-22 21:18:35+00:00,Business Finance,2015
17,564966,The Complete Chart Pattern Trading Course: A P...,True,200,2666,115,52,All Levels,4.0,2015-08-10 21:07:35+00:00,Business Finance,2015
...,...,...,...,...,...,...,...,...,...,...,...,...
3659,577796,"Simple Javascript: Learn by Doing, Beginners W...",True,25,2753,10,18,All Levels,2.0,2015-09-07 17:55:11+00:00,Web Development,2015
3667,523216,The Fastest Way to Create a Website Using Godaddy,True,30,1454,14,12,Beginner Level,0.5,2015-11-09 20:44:25+00:00,Web Development,2015
3669,679992,Building Better APIs with GraphQL,True,50,555,89,16,All Levels,2.5,2015-11-29 22:02:02+00:00,Web Development,2015
3671,667122,Build A Stock Downloader With Visual Studio 20...,True,20,436,36,22,Intermediate Level,1.5,2015-11-19 17:22:47+00:00,Web Development,2015
3675,635248,Learn and Build using Polymer,True,40,513,169,48,All Levels,3.5,2015-12-30 16:41:42+00:00,Web Development,2015

### 10.What are the Max. Number of Subscribers for each level of courses?

In [136]:
#df.groupby('level')['num_subscribers'].max()
#df.groupby('level').max()

In [138]:
df.head(1)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,year
0,1070968,Ultimate Investment Banking Course,True,200,2147,23,51,All Levels,1.5,2017-01-18 20:58:58+00:00,Business Finance,2017

In [140]:
df.level.unique()

array(['All Levels', 'Intermediate Level', 'Beginner Level',
       'Expert Level'], dtype=object)

In [144]:
df.groupby('level')['num_subscribers'].max()

level
All Levels            268923
Beginner Level        161029
Expert Level            5172
Intermediate Level     29167
Name: num_subscribers, dtype: int64

In [146]:
df.groupby('level').max()

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,content_duration,published_timestamp,subject,year
level,,,,,,,,,,,
All Levels,1277924,６時間でインターバンク市場を攻略！最短距離でトレード基礎力,True,200,268923,27445,544,76.5,2017-07-06 21:16:13+00:00,Web Development,2017
Beginner Level,1282064,７日でマスター ビギナー向け Adobe Illustrator どきどきセミナー,True,200,161029,5924,779,78.5,2017-07-06 21:46:30+00:00,Web Development,2017
Expert Level,1275790,[Value Investing] Where White People Keep Thei...,True,200,5172,249,157,12.5,2017-07-04 18:08:01+00:00,Web Development,2017
Intermediate Level,1276182,株式投資で本当のテクニカル分析ができるようになる,True,200,29167,3326,320,31.5,2017-07-05 04:41:54+00:00,Web Development,2017